baseURL = "https://liaosirui.com/"

defaultContentLanguage = "zh"
languageCode           = "zh"

title = "LiaoSirui"

copyright = 'å¤‡æ¡ˆå·: èœ€ICPå¤‡17003301å·-1'

disableKinds = ["taxonomy", "term"]
enableEmoji  = true

[author]
    headline = "a devops coder and focus on golang and k8s. ğŸ’¬"
    image    = "logo.jpeg"
    name     = "å»–æ€ç¿(Sirui Liao)"

    links = [
        { facebook = { href = "mailto:cyril@liaosirui.com", "text" = "cyril@liaosirui.com", icon = "flickr" } },
        { github = { href = "https://github.com/LiaoSirui", text = "GitHub", target = "_self" } },
        { stack-exchange = { href = "https://github.com/LiaoSirui/blog.liaosirui.com/", text = "åšå®¢", target = "_self", icon = "stack-exchange" } },
        { google = { href = "https://resume.liaosirui.com/", text = "ç®€å†", target = "_self", icon = "instagram" } },
    ]

[module]
    [module.hugoVersion]
        extended = false
        min      = "0.86.1"
